### ISSUE TITLE
Where are these CSV files from

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/hathi-test-dataset#2]
Just a question. I thought they were an extract from the hathifiles, but those are TSV. So what are these? How would we make more metadata like them?

**Comment by organisciak** [comment]
Sampling strategy is here: https://github.com/massivetexts/hathi-test-dataset/blob/master/TestingDataset.ipynb. Data was loaded from Hathifiles, sampled, and exported to a csv.

**Comment by bmschmidt** [comment]
Got it. I was just perplexed by the format change.
