### ISSUE TITLE
Add remote source for glove vectors

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/hathi-test-dataset#3]
Trying to get this running on a different computer--I don't have the GloVe vectors we're using, nor any record of what they are or where they came from. I can create a new one, but I don't know which gloVe vectors we're targetting.

**Comment by organisciak** [comment]
You mean which Glove model specifically? I'll check after lunch what I have locally for this line `from local import wem_location` (probably 840B?). At this point, I don't expect it's too important, we can swap out different ones later as we polish our workflow. For the broad strokes and at book-length scale, it probably won't change too much between models.

**Comment by organisciak** [comment]
Confirming that it's `glove.840B-300d.word2vec.bin`. It's [this download](http://nlp.stanford.edu/data/glove.840B.300d.zip) converted to Word2vec binary format with `https://github.com/marekrei/convertvec`
